# Generated by Django 4.1 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="anio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="libro",
            name="editorial",
            field=models.CharField(default="Desconocida", max_length=100),
        ),
        migrations.AddField(
            model_name="libro",
            name="isbn",
            field=models.CharField(default="---", max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="libro",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
