# Generated by Django 4.1 on 2024-11-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0003_comentario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comentario",
        ),
    ]
