# Generated by Django 4.1 on 2024-11-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0005_comentario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentario",
            name="comentario_id",
        ),
    ]
