# Generated by Django 4.1 on 2024-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0006_remove_comentario_comentario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
